import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Clock3, Facebook, Instagram, Menu, Phone, X, Youtube } from "lucide-react";
import { useEffect, useState } from "react";
import { publicNavItems } from "@/lib/publicRoutes";

const fullLogoImg = "/manus-storage/clinic-logo-user-supplied-final_13e2373e.avif";
type SiteHeaderProps = { onBookAppointment?: () => void };

function WhatsAppIcon({ size = 25 }: { size?: number }) { return <svg aria-hidden="true" viewBox="0 0 32 32" width={size} height={size} fill="currentColor"><path d="M16.02 3.2a12.8 12.8 0 0 0-10.94 19.45L3.4 28.8l6.32-1.66A12.8 12.8 0 1 0 16.02 3.2Zm0 23.3a10.5 10.5 0 0 1-5.35-1.46l-.38-.23-3.76.99 1-3.65-.25-.38a10.5 10.5 0 1 1 8.74 4.73Zm5.76-7.86c-.31-.16-1.8-.89-2.08-.99-.28-.1-.49-.16-.7.16-.2.31-.8.98-.98 1.18-.18.2-.36.22-.67.07-.31-.16-1.31-.48-2.5-1.54-.92-.82-1.54-1.83-1.72-2.14-.18-.31-.02-.47.14-.62.14-.14.31-.36.47-.54.16-.18.2-.31.31-.52.1-.2.05-.39-.03-.55-.08-.16-.7-1.68-.96-2.3-.25-.6-.51-.52-.7-.53h-.6c-.2 0-.53.08-.8.39-.28.31-1.05 1.03-1.05 2.51s1.08 2.92 1.23 3.12c.15.2 2.13 3.25 5.16 4.56.72.31 1.28.5 1.72.64.72.23 1.37.2 1.89.12.58-.09 1.76-.72 2.01-1.42.25-.7.25-1.29.17-1.42-.07-.13-.27-.2-.57-.35Z" /></svg>; }

export function SiteHeader({ onBookAppointment }: SiteHeaderProps) { const [menu, setMenu] = useState(false); const [headerScrolled, setHeaderScrolled] = useState(false); useEffect(() => { const syncHeader = () => setHeaderScrolled(window.scrollY > 52); syncHeader(); window.addEventListener("scroll", syncHeader, { passive: true }); return () => window.removeEventListener("scroll", syncHeader); }, []); const bookAppointment = () => { setMenu(false); if (onBookAppointment) onBookAppointment(); else window.location.assign("/"); }; return <><div className="topbar shared-topbar"><div className="container topbar-inner"><span>Jind’s first NABH-accredited eye hospital</span><div className="top-links"><a href="tel:+919729236700"><Phone size={13} /> +91 97292-36700</a><a href="mailto:saraswatieyecarecentre@gmail.com">saraswatieyecarecentre@gmail.com</a></div></div></div><header className={`header premium-scroll-header shared-site-header ${headerScrolled ? "header-scrolled" : ""}`}><div className="container header-inner"><a className="brand full-logo-brand" href="/"><img src={fullLogoImg} alt="Saraswati Eye Care Centre" width="432" height="75" /></a><nav className="desktop-nav">{publicNavItems.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav><div className="header-actions"><a className="phone-link capsule-action call-capsule" href="tel:+919729236700"><Phone size={16} /> <span>Call us</span></a><button type="button" className="capsule-action book-capsule shared-book-button" onClick={bookAppointment}>Book appointment <ArrowUpRight size={16} /></button><button type="button" className="menu-btn" onClick={() => setMenu(open => !open)} aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button></div></div></header><AnimatePresence>{menu && <motion.div className="mobile-menu shared-mobile-menu" initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }}><nav>{publicNavItems.map(([label, href], index) => <motion.a key={label} href={href} onClick={() => setMenu(false)} initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .06 }}>{label}<ArrowUpRight size={16} /></motion.a>)}</nav><button type="button" className="shared-mobile-book" onClick={bookAppointment}>Book appointment <ArrowUpRight size={16} /></button></motion.div>}</AnimatePresence></>; }

export function SiteFooter() { return <><footer className="footer shared-site-footer"><div className="container footer-grid"><div className="footer-brand"><a className="brand full-logo-brand footer-logo" href="/"><img src={fullLogoImg} alt="Saraswati Eye Care Centre" width="432" height="75" loading="lazy" decoding="async" /></a><p>Specialist eye care with a more human way of doing things.</p><div className="socials"><a href="https://www.youtube.com/@saraswatieyecarecentre6185" target="_blank" rel="noreferrer" aria-label="YouTube"><Youtube size={17} /></a><a href="https://www.facebook.com/people/Saraswati-Eye-care-And-Retina-Centre/100057587073474/" target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook size={17} /></a><a href="https://www.instagram.com/saraswatieyecarecentre/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17} /></a></div></div><div><p className="footer-heading">Explore</p><a href="/about">About us</a><a href="/services">Our services</a><a href="/photo">Photo gallery</a><a href="/equipment">Equipment</a><a href="/contact">Contact</a></div><div className="footer-map"><p className="footer-heading">Visit us</p><p>66/6, Rajwaha Road,<br />Opp. Bus Stand, Jind<br />Haryana – 126102</p><iframe title="Saraswati Eye Care Centre location" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Saraswati%20Eye%20Care%20Centre%20Jind&output=embed" /><a className="text-link" href="https://www.google.com/maps/dir/?api=1&destination=29.3139692,76.3253288" target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={15} /></a></div><div><p className="footer-heading">Contact</p><a href="tel:+919729236700">+91 97292-36700</a><a href="mailto:saraswatieyecarecentre@gmail.com">saraswatieyecarecentre@gmail.com</a><p className="hours"><Clock3 size={15} /> Mon–Sat · 9 AM–5 PM<br /><span>OPD 10 AM–1 PM · Sunday closed</span></p></div></div><div className="container footer-bottom"><span>© 2026 Saraswati Eye Care Centre</span><span>Built around better care.</span></div></footer><a className="whatsapp-float" href="https://wa.me/919729236700" target="_blank" rel="noreferrer" aria-label="Chat with Saraswati Eye Care Centre on WhatsApp"><WhatsAppIcon /></a></>; }
